version: '3'
services:
    app:
        build: .
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - default
            - bridge
        restart: always

    db:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=app
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_HOST=%
            - MYSQL_TCP_PORT=3306
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        volumes:
            - database-new:/var/lib/mysql
        networks:
            - default
            - bridge
        restart: always

volumes:
    database:

networks:
    default:
        name: uwu-weeb-network # network for caddy proxy
        external: true
    bridge:
        driver: bridge # bridge for internet access
        external: false
